CREATE TABLE `entornos` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`time` INT(11) NULL DEFAULT NULL,
	`pos` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`text` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`owner` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`identifier` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=30
;
